version: '3'

services:
  oop_db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./Sql:/var/www/sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oop
      MYSQL_PASSWORD: root
    ports:
      - "101:3306"
  oop:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: oop
    depends_on:
      - oop_db
    volumes:
      - ./source/oop:/var/www/html/
      - ./config/admin_vhosts:/etc/apache2/sites-enabled
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "100:80"
    stdin_open: true
    tty: true
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name : oop_phpmyadmin
    links: 
        - oop_db:db
    ports:
        - 102:80
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        PMA_USER: root
        PMA_PASSWORD: root
        # PMA_HOST: db
        PMA_PORT: 3306